secrets:
  jwt_public:
    file: ./.ops/jwt/public.pem
  jwt_private:
    file: ./.ops/jwt/private.pem

services:
  webapp:
    image: ghcr.io/wojciechem/legacy:dev-local
    build:
      dockerfile: Dockerfile
      context: .
      target: test
      tags:
        - "ghcr.io/wojciechem/legacy:dev-local"
    env_file:
      - .env
    secrets:
      - jwt_public
      - jwt_private
    volumes:
      - ./vendor:/app/vendor
      - ./src:/app/src
      - ./config:/app/config
      - ./tests:/app/tests

  nginx:
    image: nginx:1.25.1
    ports:
      - target: 80
        published: 8765
        protocol: tcp
    volumes:
      - ./.ops/server.conf.template:/etc/nginx/templates/default.conf.template/:ro
      - ./public:/app/public
    environment:
      - NGINX_HOST=localhost
      - APP_HOST=webapp
      - APP_PORT=9000
      - REDIRECT_DOMAIN=localhost:8765

#  webapp-frankenphp:
#    image: ghcr.io/wojciechem/legacy:dev-local-frankenphp
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: test
#      args:
#        - BASE_IMAGE=dunglas/frankenphp:main
##    profiles:
##      - dev
#    ports:
#      - target: 80
#        published: 8766
#        protocol: tcp

