parameters:
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Booking\:
        resource: '../src/Booking/'

    App\Operations\:
        resource: '../src/Operations/'
#        exclude:
#            - '../src/Kernel.php'
